# Build the docs on every commit
# Also deploy when pushed to 'develop' (if they built OK)

name: Documentation CI/CD
on: [push, pull_request]
jobs:
  build-docs-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: build website contents
        run: |
          cp package.yaml.pandoc package.yaml
          mkdir -p _site dist
          nix-shell --pure --run hpack
          nix-shell --pure --run "runghc ./Setup.hs configure --prefix=$PWD/out"
          nix-shell --pure --run "runghc ./Setup.hs build && runghc ./Setup.hs install"
          nix-shell --pure --run "make NO_STACK=y html"
          nix-shell --pure --run "make NO_STACK=y pdf"
          cp dist/pbook.pdf _site/book.pdf
  deploy-docs-job:
    runs-on: ubuntu-latest
    needs: build-docs-job
    # Only deploy docs from 'main' branch (and if they built OK).
    if: success() && github.ref == 'refs/heads/fd/gh-pages'
    steps:
      - uses: actions/checkout@v3
      - name: deploy website contents
        run: |
          git add _site
          git commit -a -m "updating GH-PAGES"
          git push --force-with-lease origin HEAD:gh-pages
